/**
 * Canonical public origin for the portal.
 *
 * Every SEO surface — metadataBase, canonical URLs, the sitemap, robots.txt and
 * structured data — derives from here so search engines index
 * https://doctorappraisal.co.uk instead of the Vercel deployment domain.
 * Preview deployments can override it with NEXT_PUBLIC_SITE_URL.
 */
export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL ?? "https://doctorappraisal.co.uk").replace(/\/$/, "");

export const SITE_NAME = "AppraisalPortal UK";

export const SITE_TAGLINE = "MAG 2022 appraisal, 360° feedback, CPD and PDP — for UK doctors and their appraisers.";

/** Absolute URL for a path, so canonicals and structured data never drift. */
export function absoluteUrl(path = "/"): string {
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

/**
 * Structured data (schema.org) for the product. Helps search engines understand
 * what the portal is and who it serves, including the UK revalidation context.
 */
export const STRUCTURED_DATA = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: SITE_NAME,
  applicationCategory: "HealthApplication",
  applicationSubCategory: "Medical appraisal and revalidation",
  operatingSystem: "Web",
  url: SITE_URL,
  description:
    "UK medical appraisal portal built on the MAG 2022 model form: 360° MSF feedback, CPD portfolios, SMART PDPs that carry forward, and approval-gated AI — with lock-on-sign-off, version history and an RO bundle for GMC revalidation.",
  inLanguage: "en-GB",
  audience: {
    "@type": "Audience",
    audienceType: "Doctors, appraisers and Responsible Officers in the UK",
  },
  featureList: [
    "MAG 2022 model form, section by section with autosave",
    "Anonymous 360° colleague and patient feedback (MSF)",
    "CPD record with reflections and approval-gated AI drafting",
    "SMART PDP that carries agreed objectives into the next year",
    "Appraiser review, tracked edits, comments and e-sign-off",
    "Lock on sign-off with immutable version history and audit log",
    "Responsible Officer compliance dashboard and GMC export bundle",
  ],
} as const;

/**
 * The branded social preview image, generated by src/app/og/route.tsx. Served
 * from a plain route so this URL is stable, absolute and host-independent.
 */
export const SITE_OG_IMAGE = absoluteUrl("/og");

export const SOCIAL_IMAGE = {
  url: SITE_OG_IMAGE,
  width: 1200,
  height: 630,
  alt: `${SITE_NAME} — MAG 2022 medical appraisal for UK doctors`,
};

/**
 * Open Graph block for a single page. Declaring `openGraph` on a page replaces
 * the block inherited from the layout, so pages must restate the image —
 * otherwise their preview loses its artwork (and og:url drifts to the homepage).
 */
export function pageOpenGraph(path: string) {
  return { url: absoluteUrl(path), images: [SOCIAL_IMAGE] };
}

/**
 * Site-level schema: tells search engines this origin is the canonical home of
 * the product, which pairs with the SoftwareApplication block above.
 */
export const WEBSITE_DATA = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: SITE_NAME,
  alternateName: "doctorappraisal.co.uk",
  url: SITE_URL,
  inLanguage: "en-GB",
  publisher: {
    "@type": "Organization",
    name: SITE_NAME,
    url: SITE_URL,
  },
} as const;
